version: '3.8'
services:
  flask:
    image: projet/flask-app:v0.1
    build:
      context: ./App
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=devops
      - MONGO_COLLECTION=users
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=test1234
    depends_on:
      - mongo
    networks:
      - network-falsk-mongo
 
  mongo:
    image: mongo:latest
    hostname: mongo.com
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test1234
    ports:
      - "27017:27017"
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - network-falsk-mongo
 
networks:
  network-falsk-mongo:
    driver: bridge