apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: devops-demo
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          image: ashram939/projet-flask-v0.1:3032c1424c9389d95ee62e3cf3fc9aefdb1f82c8
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: devops
            - name: MONGO_COLLECTION
              value: users
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          volumeMounts:
            - name: init-script
              mountPath: /usr/local/bin/init.sh
              subPath: init.sh
              readOnly: true
          command: ["/bin/bash", "/usr/local/bin/init.sh"]
      volumes:
        - name: init-script
          configMap:
            name: flask-init-script