apiVersion: batch/v1
kind: Job
metadata:
  name: port-forward-job
  namespace: devops-demo
spec:
  template:
    spec:
      containers:
        - name: port-forward
          image: bitnami/kubectl:latest
          command: ["/bin/bash", "-c", "chmod +x /scripts/port-forward.sh && /scripts/port-forward.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: scripts
          configMap:
            name: port-forward-scripts