# name: Docker Image CI

# on:
#   workflow_run:
#     workflows: [Docker Tests]
#     types: [completed]

# jobs:

#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Build the Docker image
#       run: docker build ./app -t ${{ secrets.DOCKER_USERNAME }}/DevOps:${{ github.sha }}
      
#     - name: Log in to Docker Registry
#       run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
#     - name: Push the Docker image
#       run: docker push ${{ secrets.DOCKER_USERNAME }}/reactcicd:${{ github.sha }}