name: Docker Tests

on:
  push:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécution des tests Pytest
      run: |
        pytest
