name: Docker Test Buil and Push

on:
  push:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r ./App/requirements.txt

    - name: Exécution des tests Pytest
      run: |
        pytest
      continue-on-error: true

  on-success:
    runs-on: ubuntu-latest
    needs: pytest
    if: ${{ needs.pytest.result == 'success' }} 

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build ./App -t ${{ secrets.DOCKER_USERNAME }}/devops:allin1
      
    - name: Log in to Docker Registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops:allin1
  
  on-failure:
    runs-on: ubuntu-latest
    needs: pytest
    if: ${{ needs.pytest.result != 'success' }}
    steps:
      - run: echo 'Le workflow ne s'est arrêté car 1 ou plusieurs tests ont échoués'
